### ISSUE TITLE
Support for squaremap

### ISSUE THREAD

**Issue by MeerBiene** [thebuildcraft/RemotePlayerWaypointsForXaero#1]
Would be nice if this plugin could also support [squaremap](https://modrinth.com/plugin/squaremap).

I went ahead and did some research. The endpoint is:
```
baseUrl + "/tiles/players.json"
```
and this is the response

```json
{"max":161,"players":[{"world":"minecraft_overworld","armor":3,"name":"MeerBiene2","x":-309,"health":20,"z":67,"uuid":"a418c7dcb5e8417b9af8a6dce420a6b2","yaw":-129.89647}]}
```

**Comment by thebuildcraft** [comment]
Thank you for the research. It was actually already on my to-do list. I want to support most (if not all) of the maps from [Map Index](https://map.roanv.nl/) eventually.
I will try to do it today.

**Comment by thebuildcraft** [comment]
I made some progress abstracting the Connection to be able to add more maps more easily. But... there is a problem with the Squaremap: it doesn't provide the Y coordinate.
![grafik](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/104298589/56cd392b-d539-49cd-b95a-63c9b5a6637e)
So I will make a configurable default Y later and finish the Squaremap support.

**Comment by thebuildcraft** [comment]
Ok. I added support for it. But I marked it as pre-release / beta for now, as I could not fully test yet. I will add support for the other maps soon.

**Comment by MeerBiene** [comment]
thank you <3

**Comment by MeerBiene** [comment]
I went ahead and tested. Squaremap Connection seems to be working but the waypoints don't seem to work. I could only test with a bedrock account via geyser, maybe that is an issue. If you want hit me up on discord (MeerBiene) and we can use my server for testing

**Comment by thebuildcraft** [comment]
Ok, thanks for testing. I will message you later today so we can test it. ( and maybe fix it...)

**Comment by thebuildcraft** [comment]
I will now close this because the support has been added, and we are just waiting for Squaremap to add the y coordinates to the player updates.
