### ISSUE TITLE
problem with map detection

### ISSUE THREAD

**Issue by TenbKaktysa** [thebuildcraft/RemotePlayerWaypointsForXaero#13]
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/135853249/36dc7b20-1d6b-438a-a8f0-9ab5b4fb5a26)
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/135853249/63eda0e7-060f-4b03-a912-d3e5cd8be90c)
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/135853249/8d86dd37-a9c0-4416-a404-6933997f2483)

**Comment by thebuildcraft** [comment]
Hi,
the link https://map.paradigm-mc.ru works fine for me. Make sure to add the detected server IP with the online map link to the config (it's best to use the in game config menu via ModMenu or (Neo)Forge's config screen). Also, make sure to set the map type to Squaremap.
