### ISSUE TITLE
Map connection failure.

### ISSUE THREAD

**Issue by Omni-MC** [thebuildcraft/RemotePlayerWaypointsForXaero#16]
Playing on mc.spitter.space. Have used my config menu to add the server and its Bluemap website https://map.spitter.space. The mod refuses to connect however. If you need any more info I'm glad to provide it.

**Comment by thebuildcraft** [comment]
Hi. Yes, some more information would be nice. Please send all errors you get and your config file.
Then I will have a look at it later.

**Comment by thebuildcraft** [comment]
Ok, so I did some testing: The Bluemap of your MC server has "overworld2", "overworld3" and "overworld4" which seem to be broken on the server side (they don't even load in the browser). This means that some HTTP GET request links the mod generates are broken and don't return the JSON data it needs. It then throws an error and doesn't even try the other links. I can fix this with some try catch or null checks. However, I'm currently trying to rewrite the mod to make it multi-loader and multi-version in one branch, so you'll have to wait a bit until I'm done with that.

**Comment by thebuildcraft** [comment]
@Omni-MC The multi-loader, multi-version port will take a bit longer than expected...
I have fixed your issue and will release an update soon so you don't have to wait any longer.
