### ISSUE TITLE
Guide to use the mod

### ISSUE THREAD

**Issue by AlexGhica101** [thebuildcraft/RemotePlayerWaypointsForXaero#23]
I installed it alongside squaremap and it dosent show me the players icons on the word map, even when i cranked up the settings of the mod to the max, do other players also need to have the mod? Does it work when the server dosen t have the plugin installed? Can i use it on a LAN servers?

**Comment by thebuildcraft** [comment]
Your client needs to have my mod and some sort of xaero's minimap and optionally xaero's worldmap installed. The server needs to have Dynmap, Squaremap, Bluemap or Pl3xMap and not my mod or xaeros mod. Nobody else needs to install my mod. But you have to be visible on the online map your server has. And you have to add the ip with the online map link to the config of my mod.
