### ISSUE TITLE
Cannot load cloth config dependency due to filenames differing

### ISSUE THREAD

**Issue by notoriouspc** [thebuildcraft/RemotePlayerWaypointsForXaero#24]
The version of cloth config that installed next to your mod using the prism launcher listed as a dependency in mods.toml calls for cloth_config, when the mod downloads as cloth-config. The game doesn't recognize the dependency and fails to launch. Changing the entry in mods.toml to cloth-config fixes the issue and the mod loads fine. 

Sorry if this was something I did wrong on my end, but I figured I should at least let it be known just in case this is helpful.

**Comment by thebuildcraft** [comment]
Hi, thanks for letting me know.
Please tell me if you are using NeoForge or Forge, what (Neo)Forge version you use, what Minecraft Version and Cloth-Config version.

**Comment by notoriouspc** [comment]
No problem.
I am using cloth config 4.17.101 (cloth-config-4.17.101-forge.jar) on Forge 36.2.39
Hope this helps!

**Comment by thebuildcraft** [comment]
Thank you.
It seems like it was changed from cloth-config in 1.16.5 to cloth_config in later versions. I will have to fix that...
