### ISSUE TITLE
forge config issues

### ISSUE THREAD

**Issue by KtooooYaaa1337** [thebuildcraft/RemotePlayerWaypointsForXaero#25]
Ok, i use forge for our modded server. On this server installed dynmap. Now i want to connect this dynmap with my xaero's map, and i... Dissapointed.
I wanted to config this mod manually, but when i looked for config, i seeing that... doesn't that configs i need. I tryed look for some manuals, i googled it, and i looked in gallery and see that mod, probably, wants me to i used "mod menu" for config this mod...
On forge modloader.
Mod menu doesn't exist on forge.
Ok, now tell me how i can config this mod manually and add link to online map, please? And put maybe manual to mod page for some morons like me?

![Снимок](https://github.com/user-attachments/assets/fd9ac63b-f1f6-4d01-9b59-f1e14e98393b)

**Comment by thebuildcraft** [comment]
Forge and NeoForge have built-in mod config screens. Just click on the "Mods" button on the title screen, select my mod and click "Config".

Also: STOP USING T-LAUNCHER !!!

**Comment by KtooooYaaa1337** [comment]
1 this is TL lefacy.
2 thx you so much!
