### ISSUE TITLE
Does not work with Minecraft Middle-Earth

### ISSUE THREAD

**Issue by Plexxl** [thebuildcraft/RemotePlayerWaypointsForXaero#3]
```json
"serverEntries": [
	{
		"maptype": "Dynmap",
		"ip": "build.mcmiddleearth.com",
		"link": "build.mcmiddleearth.com:8123/index.html"
	}
]
```

I have tried with IP addresses, with and without `http://`

**Comment by thebuildcraft** [comment]
Hi. Please try this map link: "build.mcmiddleearth.com:8123"
I think the problem is the "index..." at the end.

**Comment by thebuildcraft** [comment]
Ok. I looked at the get-requests the browser does: They are different from everything I have seen yet... I guess the server has a version of Dynmap I haven't tested yet. I will try to fix it this week.

**Comment by thebuildcraft** [comment]
I fixed it and made an update. You can download it on Modrinth. If for some reason it doesn't work, although I tested it, please let me know.
