### ISSUE TITLE
where is the config file??

### ISSUE THREAD

**Issue by Viper912** [thebuildcraft/RemotePlayerWaypointsForXaero#30]

**Comment by thebuildcraft** [comment]
The 2 files are in: <your_installation_folder>\config\remote_player_waypoints_for_xaero
--> general.json5  and  friends.json5
But if you want to edit them, I would recommend using Modmenu on Fabric or the built-in config screen on (Neo)Forge.

**Comment by Viper912** [comment]
> The 2 files are in: <your_installation_folder>\config\remote_player_waypoints_for_xaero --> general.json5 and friends.json5 But if you want to edit them, I would recommend using Modmenu on Fabric or the built-in config screen on (Neo)Forge.

i cannot find the option to set the dynmap link

**Comment by thebuildcraft** [comment]
in the config:
![grafik](https://github.com/user-attachments/assets/e776908f-5bc4-46fb-9c84-8194fb9312ed)

**Comment by Viper912** [comment]
thanks so much , is there a way i can use the WHOLE dynmap inside the game?

**Comment by thebuildcraft** [comment]
To my knowledge, currently not, sorry.
