### ISSUE TITLE
tutorial?

### ISSUE THREAD

**Issue by TGGamesYT** [thebuildcraft/RemotePlayerWaypointsForXaero#34]
hello! I may be dumb, but I just cant find the config file that whould allow me to assign online maps to a server

I also didnt find any tutorial for this so if I'd have an answer Ill make one.

also it whould be nice for a mod to display the seedmap's background and all seedmap stuff in game, from xaero's map. (just a mod idea)

**Comment by thebuildcraft** [comment]
I have already answered this in #30 
And for your mod idea: I won't make it. But you can go to the fabric discord server and request it there. There is a channel dedicated for this.

**Comment by TGGamesYT** [comment]
Alright
