### ISSUE TITLE
Will not connect to Dynmap

### ISSUE THREAD

**Issue by JPelicano** [thebuildcraft/RemotePlayerWaypointsForXaero#36]
Gives me errors saying the Dynmap link is broken and there was an error connecting. 

Dynmap and server running fine.

**Comment by thebuildcraft** [comment]
Please send me your config file, mod-version and minecraft-version.

**Comment by thebuildcraft** [comment]
Sorry, but I can't help you without more information.

**Comment by JPelicano** [comment]
Sorry, got hit by Hurricane Helene and had no power for a few days. 
Mod Version: 3.2.0
Minecraft Version: 1.20.1
Config attached. 
[general.json5.zip](https://github.com/user-attachments/files/17194723/general.json5.zip)

**Comment by thebuildcraft** [comment]
Oh no, that sounds terrible. Sorry for closing the issue so early.
As it seems, you didn't enter any server IP and link into the config. There is only an IP in the ignore-list, but not in server-entries.
Here you can add it:
![363323918-e776908f-5bc4-46fb-9c84-8194fb9312ed](https://github.com/user-attachments/assets/42e0e19a-6277-4909-8fcb-948f0e13726f)

**Comment by JPelicano** [comment]
No worries! I appreciate you helping me out. 

When I do add the server info I get these errors:
<img width="1537" alt="Screenshot 2024-09-30 at 5 38 27 PM" src="https://github.com/user-attachments/assets/56e7f988-eab9-446d-86c9-b4e84ffd3dee">
The config:
[remote_player_waypoints_for_xaero.zip](https://github.com/user-attachments/files/17196717/remote_player_waypoints_for_xaero.zip)

**Comment by JPelicano** [comment]
Hello again! 

I tried to solve the issue by switching over to BlueMap on my server but even on a different platform I can't connect. Am I formatting all my links correctly? Is there a Xaeros setting I should have on?

Thanks!

**Comment by thebuildcraft** [comment]
I was just about to look into it, sorry for letting you wait so long...
I'm getting the same error with the Dynmap link. Could you please also send me the BlueMap link? Also, did you change the setting to "Bluemap" in the config?
And you should not have to worry about the link formatting, because my code takes care of that... or at least it should :)

**Comment by JPelicano** [comment]
No worries! Just wanted to let you know. 

I did change the setting to Bluemap in the config and it still wasn't working. 

Bluemap: http://161.129.183.74:29851/#notchappleworld:-372:34:-100:266:0:0:0:1:flat

**Comment by thebuildcraft** [comment]
Bluemap is working for me:
![grafik](https://github.com/user-attachments/assets/e4f83097-df3c-4e39-a8dc-837dde3f9cca)

**Comment by JPelicano** [comment]
could you send a screenshot of the config?

**Comment by thebuildcraft** [comment]
```
{
	"enabled": true,
	"updateDelay": 2000,
	"serverEntries": [
		{
			"maptype": "Bluemap",
			"ip": "localhost",
			"link": "http://161.129.183.74:29851/#notchappleworld:-857:0:17:1081:-0.05:0.16:0:0:perspective"
		}
	],
	"defaultY": 64,
	"minimapWaypointsRenderBelow": "WHEN_PLAYER_LIST_SHOWN",
	"enablePlayerWaypoints": true,
	"enablePlayerIcons": true,
	"showAfkInTabList": true,
	"timeUntilAfk": 120,
	"showAfkTimeInTabList": true,
	"hideAfkMinutes": false,
	"unknownAfkStateColor": 6316128,
	"AfkColor": 16733440,
	"playerWaypointColor": "Black",
	"enableMarkerWaypoints": true,
	"markerWaypointColor": "Gray",
	"ignoredServers": [],
	"ignoreMarkerMessage": false,
	"debugMode": false,
	"minDistance": 0,
	"maxDistance": 100000,
	"maxIconDistance": 100000,
	"minDistanceMarker": 0,
	"maxDistanceMarker": 100000
}
```
Make sure to replace "localhost" with your server ip.

**Comment by thebuildcraft** [comment]
After you tried it, please let me know if it worked and / or close the issue. I will go sleep now, so I will respond again tomorrow.

**Comment by JPelicano** [comment]
I haven't been able to test it out yet but I'm not getting any errors. I'll take that as a good sign and close this ticket. I really appreciate your help!
