### ISSUE TITLE
Pre-emptive Support for squaremap Y-Coordinate

### ISSUE THREAD

**Issue by FordCorn** [thebuildcraft/RemotePlayerWaypointsForXaero#37]
In the pull request available here https://github.com/jpenilla/squaremap/pull/200 it adds tracking the players y-coordinate on the map. Wondering if support with a custom compiled release could be added for this mod. I could compile a .jar with this pull request merged if needed.

**Comment by thebuildcraft** [comment]
Sure, we could do that. However, not many servers would actually switch to this modified version. It would only get widespread adoption, if it's in the base squaremap. So I don't think it would be worth it.

**Comment by FordCorn** [comment]
Looks like this was added into squaremap! https://github.com/jpenilla/squaremap/pull/200

**Comment by thebuildcraft** [comment]
I know. I got notified. But Thank you for letting me know :)
I will probably release compatibility for it together with the 1.21.2 update.

**Comment by FordCorn** [comment]
Thanks man, woohoo!
