### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lur4ury** [thebuildcraft/RemotePlayerWaypointsForXaero#38]
It says Error- your squaremap link is open.
Im on macbook and i cant even find a key when its on my mod folder to activate waypoints.
Please check that you report a bug.

**Comment by thebuildcraft** [comment]
Please send me your link to the squaremap, the config file, mod-version and minecraft-version.

**Comment by thebuildcraft** [comment]
Sorry, but I can't help you without more information.
