### ISSUE TITLE
[suggestion] support for better pvp

### ISSUE THREAD

**Issue by krispyking24** [thebuildcraft/RemotePlayerWaypointsForXaero#6]
add support for Xaero's mod named better pvp as it uses the same mixin as Xaero's minimap which makes them incompatible but this mod asks specifically for Xaero's minimap

**Comment by krispyking24** [comment]
also without the mini map mod it doesn't say it needs it 
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/77263183/e99262e5-c377-40be-aa42-1e280cae25fe)

**Comment by thebuildcraft** [comment]
I don't know when I will have time for it. But I will definitely add support for "Better PvP", "Better PvP Fair Play" and "Xaeros Minimap Fair Play" (Maybe even before porting to Architectury...).
Also weird, that it doesn't say that it needs the minimap mod.

**Comment by thebuildcraft** [comment]
Hi. I have added support for it. It will be in the next release.
