### ISSUE TITLE
[bug] Markers are not updating.

### ISSUE THREAD

**Issue by user123456000** [thebuildcraft/RemotePlayerWaypointsForXaero#7]
I tried to use the mod on one server, but it didn't work. The mod receives data from the map and even displays players in afk in the tab, but refuses to update the markers on the map, that is, they simply do not exist. Although as soon as I turn on debug mode, everything starts working as it should, but this method interferes quite a bit with chat messages. It is worth noting that on another server everything worked perfectly without debug mode.

Minecraft version: 1.20.4 (I also tried 1.20.1)
Fabric version: 0.15.10
Fabric API version:  0.97.0+1.20.4
Cloth Config API version: 13.0.121+fabric
Mod Menu: 9.1.0-beta.1
No other mods were installed.

The server 1.20.4 runs on a folia fork. 
Squaremap
I also know that the server has a map management plugin that allows you to disable some functions of Xaeros, Journey, Voxel maps: caves, radar. If you want to know any more information, you can ask. There's nothing useful in the logs.

**Comment by thebuildcraft** [comment]
That can happen if the mod doesn't find the "world" / "dimension" you are in. It gets the information from the online map, because some servers have multiple overworld etc...
Could you please send me the map link, your MC in-game-name and a screenshot of you on the square map?
Note: It ignores the dimension check in debug mode. That's why it works.

**Comment by user123456000** [comment]
![image](https://github.com/thebuildcraft/RemotePlayerWaypointsForXaero/assets/140551706/fc17ab63-d213-4170-bbf3-c356deed7579)

https://map.edenor.fun/

It seems that the issue is really in the names of the dimensions on the online map. On this server they are called minecraft_overworld and minecraft_the_nether, while on another server they are simply called world and world_nether.

Unfortunately, I cannot show myself on the online map because the administrator hid me from it.

**Comment by user123456000** [comment]
Okay, that's a little sad, but thanks for the help anyway.

**Comment by thebuildcraft** [comment]
No problem.
