### ISSUE TITLE
Add Support for Pl3xMap,

### ISSUE THREAD

**Issue by That-GuyConnor** [thebuildcraft/RemotePlayerWaypointsForXaero#9]
When Trying to add Pl3xMap Unfortunatly It does not work. Is there a planned release for a version with pl3xmap?

**Comment by thebuildcraft** [comment]
Pl3xMap support is already on my To-do-list, but without a planned release. I currently don't have that much time and what to convert the project to a multi-loader multi-version architecture before adding anything new.

**Comment by That-GuyConnor** [comment]
thank you does this not have a planned release? or estimate?

**Comment by thebuildcraft** [comment]
Unfortunately no. As I said, my free time is currently limited, and I'm still trying to figure out an optimal way to make the mod multi-version and multi-platform.
So I'm sorry, but you will have to wait and see. I will let you know when the support has been added.

**Comment by thebuildcraft** [comment]
Hello, Pl3xMap support is now working. It will be included in the next version.
